name: DepositWithdrawal Test
on:
  push:
    paths:
      - '**'

jobs:
  env-setting:
    name: Deposit_WithdrawalTest_Devent
    runs-on: ubuntu-latest

    steps:
          - name: Checkout
            uses: actions/checkout@v3

          # Declares the repository safe and not under dubious ownership.
          - name: Add repository to git safe directories
            run: git config --global --add safe.directory $GITHUB_WORKSPACE

          - name: Install Geth
            uses: gacts/install-geth-tools@v1
            with:
              version: '1.13.4'

          - name: Setup Go
            uses: actions/setup-go@v3
            with:
              go-version: '1.21'

          - name: Copy files from Docker container
            run: |
              container_id=$(docker create onthertech/titan-ci-builder:latest)
              mkdir -p $HOME/bin
              docker cp $container_id:/usr/local/bin/cast $HOME/bin/
              docker cp $container_id:/usr/local/bin/anvil $HOME/bin/
              docker cp $container_id:/usr/local/bin/forge $HOME/bin/
              docker rm $container_id

          - name: Set execute permissions and add to PATH
            run: |
              chmod +x $HOME/bin/*
              echo "$HOME/bin" >> $GITHUB_PATH

          - name: install pnpm
            run: npm install -g pnpm@8

          - name: build necessary files for @eth-optimism/core-utils
            run: pnpm run build

          - name: Install submodule for test.sol
            run: |
              git submodule init
              git submodule update

          - name: Install submodule for test.sol2
            run: |
              cd packages/contracts-bedrock/lib/forge-std/lib/ds-test
              git submodule init
              git submodule update
              cd ../../../../../..

          - name: Run devnet-up command
            run: make devnet-up

          - name: cd to tokamak-titan-canyon/packages/sdk and execute test code
            run: |
              cd packages/sdk
              npx hardhat deposit-eth --amount 40 --to 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC --network devnetL1
