name: DepositWithdrawal Test
on:
  push:
    paths:
      - '**'

jobs:
  env-setting:
    name: Os-Stetting-Deposit_WithdrawalTest
    runs-on: ubuntu-latest
    container:
      image: onthertech/titan-ci-builder:latest


    steps:
          - name: Checkout
            uses: actions/checkout@v3

          # Declares the repository safe and not under dubious ownership.
          - name: Add repository to git safe directories
            run: git config --global --add safe.directory $GITHUB_WORKSPACE

          - name: Restore PNPM Package Cache
            uses: actions/cache@v3
            with:
              path: node_modules
              key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

          - name: Save PNPM Package Cache
            uses: actions/cache@v3
            with:
              path: node_modules
              key: pnpm-packages-v2-${{ hashFiles('pnpm-lock.yaml') }}

          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '20'

          - name: install pnpm
            run: npm install -g pnpm@8

          - name: Setup Python
            uses: actions/setup-python@v3
            with:
              python-version: '3.9'

          - name: Setup Go
            uses: actions/setup-go@v3
            with:
              go-version: '1.21'

          - run: geth version
          - run: abigen --version
          - run: bootnode -h
          - run: clef --version
          - run: evm --version
          - run: rlpdump -h


          - name: Verify versions
            run: |
              git --version
              go version
              node --version
              pnpm --version
              make --version
              geth version
              forge --version

          - name: Copy binary files from Docker container
            run: |
              container_id=$(docker create onthertech/titan-ci-builder:latest)
              mkdir -p $HOME/bin
              docker cp $container_id:/usr/local/bin/cast $HOME/bin/
              docker cp $container_id:/usr/local/bin/anvil $HOME/bin/
              docker cp $container_id:/usr/local/bin/forge $HOME/bin/
              docker rm $container_id

          - name: Set execute permissions and add to PATH
            run: |
              chmod +x $HOME/bin/*
              echo "$HOME/bin" >> $GITHUB_PATH


          - name: Install dependencies
            run: |
              pnpm install

          - name: build necessary files for @eth-optimism/core-utils
            run: pnpm run build

          - name: Install submodule for test.sol
            run: |
              git submodule init
              git submodule update

          - name: Install submodule for test.sol2
            run: |
              cd packages/contracts-bedrock/lib/forge-std/lib/ds-test
              git submodule init
              git submodule update
              cd ../../../../../..

          - name: Run devnet-up command
            run: make devnet-up

          - name: cd to tokamak-titan-canyon/packages/sdk and execute test code
            run: |
              cd packages/sdk
              npx hardhat deposit-eth --amount 40 --to 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC --network devnetL1







