name: geth unit tests

on:
  push:
    paths:
      - '**'

defaults:
  run:
    working-directory: ./op-e2e

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.21
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install
      run: make

    - name: Test
      run: make test
