name: slither analysis

on:
  push:
    paths:
      - '**'

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  slither:
    name: Slither run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Update npm
        run: npm install -g npm@latest

      - name: Copy foundry from Docker container
        run: |
          container_id=$(docker create onthertech/titan-ci-builder:latest)
          mkdir -p $HOME/bin
          docker cp $container_id:/usr/local/bin/cast $HOME/bin/
          docker cp $container_id:/usr/local/bin/anvil $HOME/bin/
          docker cp $container_id:/usr/local/bin/forge $HOME/bin/
          docker rm $container_id

      - name: Set permissions_add PATH
        run: |
          chmod +x $HOME/bin/*
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm store dir)"

      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        # only install dependencies if there was a change in the deps
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: |
          npm install -g pnpm@latest
          cd packages/tokamak/contracts-bedrock
          pnpm install

      - name: Build
        run: pnpm run build

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install solc-select and solc
        run: |
          pip3 install solc-select
          solc-select install 0.8.15
          solc-select use 0.8.15
          echo "SOLC_VERSION=0.8.15" >> $GITHUB_ENV

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Run Slither
        uses: crytic/slither-action@v0.3.1
        id: slither
        with:
          target: packages/tokamak/contracts-bedrock/src/L1
          slither-config: packages/tokamak/contracts-bedrock/slither.config.json
          fail-on: config
          slither-version: dev-triage-db
          slither-args: --triage-database packages/tokamak/contracts-bedrock/slither.db.json
          ignore-compile: true
          continue-on-error: true







