name: slither analysis

on:
  push:
    paths:
      - '**'

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  slither:
    name: Slither run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Copy foundry from Docker container
        run: |
          container_id=$(docker create onthertech/titan-ci-builder:latest)
          mkdir -p $HOME/bin
          docker cp $container_id:/usr/local/bin/cast $HOME/bin/
          docker cp $container_id:/usr/local/bin/anvil $HOME/bin/
          docker cp $container_id:/usr/local/bin/forge $HOME/bin/
          docker rm $container_id

      - name: Set permissions_add PATH
        run: |
          chmod +x $HOME/bin/*
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm store dir)"

      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        # only install dependencies if there was a change in the deps
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: |
          npm i -g pnpm
          pnpm install

      - name: Build
        run: pnpm run build

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Run analysis
        working-directory: ./packages/tokamak/contracts-bedrock
        run: |
          slither src/L1
          continue-on-error: true
