name: slither analysis

on:
  push:
    paths:
      - '**'

jobs:
  slither:
    name: Slither run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Run Slither
        uses: crytic/slither-action@v0.3.1
        id: slither
        with:
          target: packages/tokamak/contracts-bedrock
          slither-config: packages/tokamak/contracts-bedrock/slither.config.json
          fail-on: config
          slither-version: dev-triage-db
          slither-args: --triage-database packages/tokamak/contracts-bedrock/slither.db.json
          continue-on-error: true
